import React from 'react'
import '../globals.css'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const layoutAdmin = ({ children }) => {
    return (
        <html lang='en'>
            <body>
                Dashboard Layout
                {children}
            </body>
        </html>
    )
}

export default layoutAdmin