export const metadata = {
  title: "Shop Layout",
  description: "Shop - Generated by create next app",
};

import TitlePage from '@/components/pagesComponents/TitlePage'
import React from 'react'

const Id = ({params}) => {
    console.log(params)
  return (
    <div>
        <TitlePage title='Id'/>
    </div>
  )
}

export default Id
