
import TitlePage from '@/components/pagesComponents/TitlePage'
import React from 'react'
import { POST } from '../page'
import Link from 'next/link'

export function generateMetadata({params}){
  const post = POST.find((post) => post.slug === params.slug)
  return{
    title: post.title,
    description: post.title + 'Blog - Generated by create next app'
  }
}

const Slug = ({ params }) => {
  const post = POST.find((post) => post.slug === params.slug)


  return (
    <div>
      <TitlePage title={post.title} />
      <div className='text-center'>
        <p className='text-center'>{post.content}</p>
        <Link href='/blog'>Volver</Link>
      </div>
    </div>
  )
}

export default Slug
